### ISSUE TITLE
run the code on Windows 10

### ISSUE THREAD

**Issue by ardeal** [zisianw/FaceBoxes.PyTorch#17]
Hi,

The code couldn't be run on Windows 10.
Do you have any solution to run the code on Windows 10?

Thanks and Best Regards,
Ardeal

**Comment by ardeal** [comment]
Hi,
I tried to run the code on Windows 10 and Python3.5, but I got the following error messgages:

```Python
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/code_python/mtcnn/FaceBoxes_PyTorch/test.py", line 9, in <module>
    from utils.nms_wrapper import nms
  File "D:\code_python\mtcnn\FaceBoxes_PyTorch\utils\nms_wrapper.py", line 8, in <module>
    from .nms.cpu_nms import cpu_nms, cpu_soft_nms
ImportError: No module named 'utils.nms.cpu_nms'

```


Do you have any solution about the upper issue?

Thanks and Best Regards,
Ardeal

**Comment by zisianw** [comment]
Hi @ardeal, you need to first compile nms. In linux, it follows the commands in .`/make.sh`. I'm not sure how it works in Windows. Alternatively, you can try using numpy version of nms, following [this post](https://github.com/zisianw/FaceBoxes.PyTorch/issues/4#issuecomment-459592536).

**Comment by chungyau97** [comment]
@zisianw I use git-bash to run ./make.sh, I comment out all related to cuda but that's one issue in window 
![capture](https://user-images.githubusercontent.com/33013947/54005658-40868100-4195-11e9-998c-f3da96cbd344.PNG)

**Comment by xsacha** [comment]
You can reimplement or replace the NMS. I wrote something very quickly in C++ that performs the NMS with similar accuracy.
